// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT3t7iVJmmV6ceeiA0pmWEr6KCt9tkCPk',
    appId: '1:373897372218:web:2e384a7290b2c38459cb03',
    messagingSenderId: '373897372218',
    projectId: 'portable-weather-station-59641',
    authDomain: 'portable-weather-station-59641.firebaseapp.com',
    databaseURL: 'https://portable-weather-station-59641-default-rtdb.firebaseio.com',
    storageBucket: 'portable-weather-station-59641.firebasestorage.app',
    measurementId: 'G-ED336NGYNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxe1o0W4uvIrCWQpzMBiatgXYUOPvoEvA',
    appId: '1:373897372218:android:658b31d9eabd5a8c59cb03',
    messagingSenderId: '373897372218',
    projectId: 'portable-weather-station-59641',
    databaseURL: 'https://portable-weather-station-59641-default-rtdb.firebaseio.com',
    storageBucket: 'portable-weather-station-59641.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKn4PTK4XiitmdajN0GNMl0eQY7hO7hPk',
    appId: '1:373897372218:ios:d36c61a7e72bf94e59cb03',
    messagingSenderId: '373897372218',
    projectId: 'portable-weather-station-59641',
    databaseURL: 'https://portable-weather-station-59641-default-rtdb.firebaseio.com',
    storageBucket: 'portable-weather-station-59641.firebasestorage.app',
    iosBundleId: 'com.example.iotBasedWeatherStation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKn4PTK4XiitmdajN0GNMl0eQY7hO7hPk',
    appId: '1:373897372218:ios:d36c61a7e72bf94e59cb03',
    messagingSenderId: '373897372218',
    projectId: 'portable-weather-station-59641',
    databaseURL: 'https://portable-weather-station-59641-default-rtdb.firebaseio.com',
    storageBucket: 'portable-weather-station-59641.firebasestorage.app',
    iosBundleId: 'com.example.iotBasedWeatherStation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT3t7iVJmmV6ceeiA0pmWEr6KCt9tkCPk',
    appId: '1:373897372218:web:c7a86c67503282a559cb03',
    messagingSenderId: '373897372218',
    projectId: 'portable-weather-station-59641',
    authDomain: 'portable-weather-station-59641.firebaseapp.com',
    databaseURL: 'https://portable-weather-station-59641-default-rtdb.firebaseio.com',
    storageBucket: 'portable-weather-station-59641.firebasestorage.app',
    measurementId: 'G-7D0JC7QE6S',
  );

}